version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 99
  reviewers:
  - njzjz
  assignees:
  - njzjz
  ignore:
  - dependency-name: "@waline/hexo-next"
    versions:
    - 1.0.6
    - 1.0.8
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: hexo-image-cloudflare
    versions:
    - 0.2.2
    - 0.2.4
  - dependency-name: hexo-tag-publications
    versions:
    - 0.0.10
    - 0.0.9
    - 0.1.10
    - 0.1.4
    - 0.1.5
    - 0.1.7
    - 0.1.9
  - dependency-name: hexo-theme-next
    versions:
    - 8.2.1
    - 8.2.2
  - dependency-name: hexo
    versions:
    - 5.4.0
  - dependency-name: hexo-tag-bilitube
    versions:
    - 0.1.3
    - 0.1.4
    - 0.1.5
    - 0.1.6
    - 0.1.8
    - 0.1.9
  - dependency-name: hexo-source-tag
    versions:
    - 0.0.11
    - 0.0.12
  - dependency-name: "@njzjz/hexo-sitemap"
    versions:
    - 0.0.2
