# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jinzhe Zeng's Blog
subtitle: 苟利国家生死以，岂因祸福避趋之
description: PhD candidate at Rutgers University
keywords: Jinzhe Zeng Blog
author: Jinzhe Zeng
language:
  - en
  - zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://njzjz.win
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
marked:
  lazyload: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/njzjz/njzjz.github.io
  branch: master
minify:
  gzip:
    enable: false
  brotli:
    enable: false
  xml:
    enable: true
  json:
    enable: true

sitemap:
  path: sitemap.xml
hide_posts:
  public_generators:
    - tag
    - category
    - sitemap
    - feed
  noindex: false

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false

search:
  path: search.xml
  field: post
  content: true
  format: striptags

cdn:
  use_webp: true
  native: true
  exclude_domains:
    - https://images.weserv.nl/
    - https://img.njzjz.win/
    - https://unpkg.com/
    - https://pubs.acs.org/
    - https://www.mdpi.com/
  max_width:
    - 828
    - 1656
    - 378
    - 678

pwa:
  manifest:
    body:
      name: Jinzhe Zeng's Blog
      display: standalone
  serviceWorker:
    precache:
      posts:
        enable: false
      pages: false
    options:
      runtimeCaching:
        - urlPattern: regexp:\/$
          handler: NetworkFirst
          options:
            cacheName: html
        - urlPattern: regexp:\.html$
          handler: NetworkFirst
          options:
            cacheName: html
        - urlPattern: regexp:\.(?:js|css)$
          handler: StaleWhileRevalidate
          options:
            cacheName: js-css
        - urlPattern: regexp:^https:\/\/unpkg\.com
          handler: StaleWhileRevalidate
          options:
            cacheName: unpkg
        - urlPattern: regexp:^https:\/\/images\.weserv\.nl
          handler: CacheFirst
          options:
            cacheName: imagesweserv
            expiration:
              maxEntries: 60
              maxAgeSeconds: 2592000
      offlineGoogleAnalytics: true
waline:
  enable: true
  serverURL: https://comment.njzjz.win
  pageview: true
  dark: auto
  login: force
pub_author:
  - Jinzhe Zeng
  - Jin-Zhe Zeng
